//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "documents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub document_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub doc_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub session_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub checkpoint_id: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_large: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding: Option<String>,
    pub version_number: Option<i32>,
    pub parent_version_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub updated_by: Option<String>,
    pub content_size: Option<i32>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub slug: Option<String>,
    pub tags: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub purpose: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub latest_changes: Option<String>,
    pub business_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::businesses::Entity",
        from = "Column::BusinessId",
        to = "super::businesses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Businesses,
    #[sea_orm(has_many = "super::document_checkpoint_links::Entity")]
    DocumentCheckpointLinks,
    #[sea_orm(has_many = "super::document_versions::Entity")]
    DocumentVersions,
}

impl Related<super::businesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Businesses.def()
    }
}

impl Related<super::document_checkpoint_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentCheckpointLinks.def()
    }
}

impl Related<super::document_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
