//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "document_checkpoint_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub link_id: Uuid,
    pub document_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub checkpoint_id: String,
    pub linked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub linked_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::documents::Entity",
        from = "Column::DocumentId",
        to = "super::documents::Column::DocumentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Documents,
}

impl Related<super::documents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Documents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
