//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eg_assets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    pub file_extension: String,
    pub file_size_bytes: Option<i64>,
    pub category: Option<String>,
    pub category_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub marketing_funnel: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((3, 1)))", nullable)]
    pub quality_score: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub raw_ai_json: Option<Json>,
    pub analysis_timestamp: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub business_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::businesses::Entity",
        from = "Column::BusinessId",
        to = "super::businesses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Businesses,
    #[sea_orm(has_many = "super::eg_asset_brand_elements::Entity")]
    EgAssetBrandElements,
    #[sea_orm(has_many = "super::eg_asset_colors::Entity")]
    EgAssetColors,
    #[sea_orm(has_many = "super::eg_asset_objects::Entity")]
    EgAssetObjects,
    #[sea_orm(has_many = "super::eg_asset_people::Entity")]
    EgAssetPeople,
    #[sea_orm(has_many = "super::eg_asset_products::Entity")]
    EgAssetProducts,
    #[sea_orm(has_many = "super::eg_asset_projects::Entity")]
    EgAssetProjects,
    #[sea_orm(has_many = "super::eg_asset_tags::Entity")]
    EgAssetTags,
    #[sea_orm(
        belongs_to = "super::eg_content_categories::Entity",
        from = "Column::CategoryId",
        to = "super::eg_content_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EgContentCategories,
}

impl Related<super::businesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Businesses.def()
    }
}

impl Related<super::eg_asset_brand_elements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetBrandElements.def()
    }
}

impl Related<super::eg_asset_colors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetColors.def()
    }
}

impl Related<super::eg_asset_objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetObjects.def()
    }
}

impl Related<super::eg_asset_people::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetPeople.def()
    }
}

impl Related<super::eg_asset_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetProducts.def()
    }
}

impl Related<super::eg_asset_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetProjects.def()
    }
}

impl Related<super::eg_asset_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetTags.def()
    }
}

impl Related<super::eg_content_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgContentCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
