//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eg_asset_colors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub asset_id: i32,
    pub color_name: String,
    pub hex_code: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub percentage: Option<Decimal>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::eg_assets::Entity",
        from = "Column::AssetId",
        to = "super::eg_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EgAssets,
}

impl Related<super::eg_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
