//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eg_asset_projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub asset_id: i32,
    pub project_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::eg_assets::Entity",
        from = "Column::AssetId",
        to = "super::eg_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EgAssets,
    #[sea_orm(
        belongs_to = "super::eg_projects::Entity",
        from = "Column::ProjectId",
        to = "super::eg_projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EgProjects,
}

impl Related<super::eg_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssets.def()
    }
}

impl Related<super::eg_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgProjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
