//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "eg_projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: Option<DateTime>,
    pub business_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::businesses::Entity",
        from = "Column::BusinessId",
        to = "super::businesses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Businesses,
    #[sea_orm(has_many = "super::eg_asset_projects::Entity")]
    EgAssetProjects,
}

impl Related<super::businesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Businesses.def()
    }
}

impl Related<super::eg_asset_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EgAssetProjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
