//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod businesses;
pub mod document_checkpoint_links;
pub mod document_versions;
pub mod documents;
pub mod eg_asset_brand_elements;
pub mod eg_asset_colors;
pub mod eg_asset_objects;
pub mod eg_asset_people;
pub mod eg_asset_products;
pub mod eg_asset_projects;
pub mod eg_asset_tags;
pub mod eg_assets;
pub mod eg_content_categories;
pub mod eg_projects;
