//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::document_checkpoint_links::Entity as DocumentCheckpointLinks;
pub use super::document_versions::Entity as DocumentVersions;
pub use super::documents::Entity as Documents;
pub use super::eg_asset_brand_elements::Entity as EgAssetBrandElements;
pub use super::eg_asset_colors::Entity as EgAssetColors;
pub use super::eg_asset_objects::Entity as EgAssetObjects;
pub use super::eg_asset_people::Entity as EgAssetPeople;
pub use super::eg_asset_products::Entity as EgAssetProducts;
pub use super::eg_asset_projects::Entity as EgAssetProjects;
pub use super::eg_asset_tags::Entity as EgAssetTags;
pub use super::eg_assets::Entity as EgAssets;
pub use super::eg_content_categories::Entity as EgContentCategories;
pub use super::eg_projects::Entity as EgProjects;
