import { test, expect } from "@playwright/test";
import { closeAllE2EWindows, closeE2EWindow, closeTauri, getPageDiagnostics, openE2EWindow } from "./tauri";

// P2.6 Extended — AI-Mediated Output + MCP Control Loop
// SYSTEM LAWS:
//   1. UI must NEVER render raw model output
//   2. Model output must ALWAYS be interpreted before use
//   3. Tool calls must NEVER be visible to user
//   4. System payloads must NEVER reach UI
//   5. Final response MUST ALWAYS be generated by AI
//   6. Streaming must only emit VERIFIED HUMAN TEXT
//   7. No regex-based sanitization allowed anywhere in pipeline
test.describe("Chat + MCP Isolation", () => {
  test.describe.configure({ mode: "serial" });
  test.setTimeout(120000);

  test.afterAll(async () => {
    await closeAllE2EWindows();
    await closeTauri();
  });

  const navigateToChat = async (page: any) => {
    await page.getByTitle("Chat", { exact: true }).click();
    await page.waitForTimeout(1500);
  };

  const sendMessage = async (page: any, text: string) => {
    const input = page.locator("textarea").or(page.locator('input[type="text"]')).first();
    await expect(input).toBeVisible({ timeout: 15000 });
    await input.fill(text);
    await page
      .getByTestId("chat-send")
      .or(page.getByRole("button", { name: /send/i }))
      .first()
      .click();
  };

  const waitForStreamEnd = async (page: any) => {
    await page.waitForFunction(
      () => document.querySelector("[data-testid='delivery-status'][data-status='pending']") === null,
      { timeout: 60000 }
    );
  };

  // ─── TEST 1: Normal chat — no MCP trigger ──────────────────────────────
  test("TEST1: normal chat — no MCP trigger, no tool approval modal", async () => {
    const { page, label } = await openE2EWindow();
    const consoleLogs: string[] = [];
    page.on("console", (msg: any) => consoleLogs.push(`[${msg.type()}] ${msg.text()}`));

    try {
      await navigateToChat(page);
      await sendMessage(page, "hi");
      await waitForStreamEnd(page);

      // ASSERT: no tool approval modal
      const modal = page.getByTestId("tool-approval-modal");
      const modalVisible = await modal.count() > 0;
      expect(modalVisible, "Tool approval modal must NOT appear for normal chat").toBe(false);

      // ASSERT: response is visible
      const assistantMsgs = page.locator(".flex.justify-start .group");
      const count = await assistantMsgs.count();
      expect(count, "Assistant response must be visible").toBeGreaterThan(0);

      // ASSERT: no raw JSON in output
      const rawJson = page.getByText(/"tool_call"/);
      const hasJson = await rawJson.count() > 0;
      expect(hasJson, 'Raw "tool_call" JSON must not be visible').toBe(false);

      console.log("[E2E] TEST1 PASSED: normal chat, no MCP trigger");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 2: Tool keyword — MCP disabled, still no trigger ─────────────
  test("TEST2: tool keyword input — MCP disabled, no auto-execution", async () => {
    const { page, label } = await openE2EWindow();
    const consoleLogs: string[] = [];
    page.on("console", (msg: any) => consoleLogs.push(`[${msg.type()}] ${msg.text()}`));

    try {
      await navigateToChat(page);
      await sendMessage(page, "execute the file listing tool");
      await waitForStreamEnd(page);

      // ASSERT: MCP is DISABLED (Phase 1 kill switch), no approval modal
      const modal = page.getByTestId("tool-approval-modal");
      const modalVisible = await modal.count() > 0;
      expect(modalVisible, "Approval modal must NOT appear — MCP_ENABLED is false").toBe(false);

      // ASSERT: response is plain text, no JSON
      const assistantMsgs = page.locator(".flex.justify-start .group");
      expect(await assistantMsgs.count()).toBeGreaterThan(0);
      const msgText = await assistantMsgs.last().textContent();
      expect(msgText?.includes('{"tool_call"'), "No raw tool_call JSON in response").toBe(false);

      console.log("[E2E] TEST2 PASSED: tool keyword, MCP disabled, no auto-execution");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 3: Clean UI output — sanitization works ──────────────────────
  test("TEST3: output is sanitized — no JSON visible, only human-readable text", async () => {
    const { page, label } = await openE2EWindow();

    try {
      await navigateToChat(page);

      const messages = ["explain what AI is", "what is a neural network", "what is 2+2"];
      for (const msg of messages) {
        await sendMessage(page, msg);
        await waitForStreamEnd(page);
        await page.waitForTimeout(500);
      }

      // ASSERT: no raw JSON anywhere in the message list
      const allMsgText = await page.locator(".flex.justify-start .group").allTextContents();
      for (const text of allMsgText) {
        expect(
          text.includes('{"tool_call"') || text.includes('"tool_calls"'),
          `No tool_call JSON visible in: ${text.slice(0, 80)}`
        ).toBe(false);
      }

      console.log("[E2E] TEST3 PASSED: all messages sanitized, no JSON visible");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 4: Mixed input — chat stays dominant ──────────────────────────
  test("TEST4: mixed input — chat is always dominant, no random MCP", async () => {
    const { page, label } = await openE2EWindow();

    try {
      await navigateToChat(page);

      const mixedMessages = [
        "hello",
        "what tools do you have",
        "hi there",
        "how are you",
      ];

      for (const msg of mixedMessages) {
        await sendMessage(page, msg);
        await waitForStreamEnd(page);

        // No approval modal at any point
        const modal = page.getByTestId("tool-approval-modal");
        const modalVisible = await modal.count() > 0;
        expect(modalVisible, `No approval modal for: "${msg}"`).toBe(false);

        await page.waitForTimeout(300);
      }

      const assistantMsgs = page.locator(".flex.justify-start .group");
      const finalCount = await assistantMsgs.count();
      console.log(`[E2E] TEST4: ${finalCount} assistant messages, no MCP auto-trigger`);
      expect(finalCount).toBeGreaterThanOrEqual(mixedMessages.length);

      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 5: Stress — no crashes, no loops ─────────────────────────────
  test("TEST5: stress — rapid messages, no crashes or loops", async () => {
    const { page, label } = await openE2EWindow();
    const pageErrors: string[] = [];
    page.on("pageerror", (err: any) => pageErrors.push(err.message));

    try {
      await navigateToChat(page);

      const stressMessages = ["hi", "explain AI", "what is 1+1", "tell me a joke"];

      for (const msg of stressMessages) {
        await sendMessage(page, msg);
        await waitForStreamEnd(page);
        await page.waitForTimeout(200);
      }

      // ASSERT: no uncaught errors
      const critical = pageErrors.filter((e) => /critical|uncaught|chunk load/i.test(e));
      expect(critical, "No critical page errors during stress").toHaveLength(0);

      // ASSERT: streaming state is reset (send button re-enabled)
      const sendBtn = page.getByTestId("chat-send").or(page.getByRole("button", { name: /send/i })).first();
      const isDisabled = await sendBtn.getAttribute("disabled");
      expect(isDisabled, "Send button must be re-enabled after stress test").toBeNull();

      console.log("[E2E] TEST5 PASSED: stress test, no crashes");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 6 (Phase 8 TEST2): Long explanation — smooth streaming ────────
  test("TEST6: long explanation — smooth streaming, no JSON, complete answer", async () => {
    const { page, label } = await openE2EWindow();
    const pageErrors: string[] = [];
    page.on("pageerror", (err: any) => pageErrors.push(err.message));

    try {
      await navigateToChat(page);
      await sendMessage(page, "Explain AI in 7 lines");
      await waitForStreamEnd(page);

      // ASSERT: response is visible and has meaningful length
      const assistantMsgs = page.locator(".flex.justify-start .group");
      expect(await assistantMsgs.count()).toBeGreaterThan(0);
      const msgText = await assistantMsgs.last().textContent() ?? "";
      expect(msgText.length, "Response must be substantial (not empty)").toBeGreaterThan(40);

      // ASSERT: no raw JSON in response
      expect(msgText.includes('{"tool_call"') || msgText.includes('"tool_calls"')).toBe(false);

      // ASSERT: response time badge is present
      const rtBadge = page.locator("[title='Full response time']");
      expect(await rtBadge.count(), "Response time badge must appear").toBeGreaterThan(0);

      // ASSERT: no page errors
      const critical = pageErrors.filter((e) => /critical|uncaught/i.test(e));
      expect(critical).toHaveLength(0);

      console.log("[E2E] TEST6 PASSED: long explanation, clean streaming");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });

  // ─── TEST 7 (Phase 8 TEST4): System payload firewall ───────────────────
  test("TEST7: response time badge visible after every assistant message", async () => {
    const { page, label } = await openE2EWindow();

    try {
      await navigateToChat(page);

      const queries = ["hello", "what is 2+2", "what is typescript"];
      for (const q of queries) {
        await sendMessage(page, q);
        await waitForStreamEnd(page);
        await page.waitForTimeout(300);
      }

      // ASSERT: every completed assistant message has a response time badge
      const allBadges = page.locator("[title='Full response time']");
      const badgeCount = await allBadges.count();
      expect(badgeCount, "Every assistant message must have response time badge").toBeGreaterThanOrEqual(queries.length);

      // ASSERT: no raw JSON or system payload keys visible anywhere
      const allText = await page.locator(".flex.justify-start .group").allTextContents();
      for (const t of allText) {
        const hasSystemKey =
          t.includes("delegation_strategy") ||
          t.includes("enable_council") ||
          t.includes("request_rationale") ||
          t.includes('{"tool_call"');
        expect(hasSystemKey, `No system payload or tool JSON in: ${t.slice(0, 60)}`).toBe(false);
      }

      console.log("[E2E] TEST7 PASSED: response time visible, no system payloads");
      const diag = getPageDiagnostics(page);
      if (diag.length) console.log("[E2E] diag:", diag.join("\n"));
    } finally {
      await closeE2EWindow(label);
    }
  });
});
