import { AgentDefinition, AGENT_PRESET_COLORS } from '../domain/AgentTypes';

const agentDefinitions: AgentDefinition[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic\'s terminal-based AI coding agent with Claude 4 Sonnet',
    icon: '\u{1F916}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.claude,
    detectionCommand: ['where', 'claude'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@anthropic-ai/claude-code'],
    installUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    launchCommand: ['claude'],
    launchArgs: [],
    supportsProviderSelection: true,
    configFilePath: '~/.claude.json',
    configDocUrl: 'https://docs.anthropic.com/en/docs/claude-code/configuration',
    homepage: 'https://claude.ai',
    version: 'latest',
  },
  {
    id: 'opencode',
    name: 'OpenCode CLI',
    description: 'Terminal-native AI coding agent by OpenCode (already integrated)',
    icon: '\u{1F4A1}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.opencode,
    detectionCommand: ['where', 'opencode'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', 'opencode'],
    launchCommand: ['opencode'],
    supportsProviderSelection: true,
    configFilePath: '~/.config/opencode/opencode.json',
    homepage: 'https://opencode.ai',
  },
  {
    id: 'codex-cli',
    name: 'OpenAI Codex CLI',
    description: 'OpenAI\'s terminal agent for coding tasks powered by GPT-4o',
    icon: '\u{1F4BB}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.codex,
    detectionCommand: ['where', 'codex'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@openai/codex'],
    installUrl: 'https://github.com/openai/codex',
    launchCommand: ['codex'],
    launchArgs: [],
    supportsProviderSelection: true,
    homepage: 'https://openai.com',
  },
  {
    id: 'claude-cowork',
    name: 'Claude Cowork',
    description: 'Collaborative AI coding agent that works alongside you in the terminal',
    icon: '\u{1F91D}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.cowork,
    detectionCommand: ['where', 'cowork'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', 'claude-cowork'],
    launchCommand: ['cowork'],
    supportsProviderSelection: true,
    homepage: 'https://github.com/anthropics/claude-cowork',
  },
  {
    id: 'hermes-agent',
    name: 'Hermes Agent',
    description: 'Open-source AI coding agent with planning and tool execution capabilities',
    icon: '\u{1F4C8}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.hermes,
    detectionCommand: ['where', 'hermes'],
    installMethod: 'pip',
    installCommand: ['pip', 'install', 'hermes-agent'],
    installUrl: 'https://github.com/NousResearch/hermes-agent',
    launchCommand: ['hermes'],
    supportsProviderSelection: true,
    homepage: 'https://hermes.ai',
  },
  {
    id: 'factory-droid',
    name: 'Factory Droid',
    description: 'AI coding agent for automated code generation and refactoring',
    icon: '\u{1F916}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.droid,
    detectionCommand: ['where', 'droid'],
    installMethod: 'pip',
    installCommand: ['pip', 'install', 'factory-droid'],
    installUrl: 'https://github.com/FactoryAI/droid',
    launchCommand: ['droid'],
    supportsProviderSelection: true,
    homepage: 'https://factory.ai',
  },
  {
    id: 'cursor-cli',
    name: 'Cursor CLI',
    description: 'AI-powered code editor CLI with built-in agent capabilities',
    icon: '\u{2728}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.cursor,
    detectionCommand: ['where', 'cursor'],
    installMethod: 'manual',
    installCommand: [],
    installUrl: 'https://cursor.sh',
    postInstallNotes: 'Cursor CLI is bundled with the Cursor IDE. Install Cursor from cursor.sh',
    launchCommand: ['cursor', '--cli'],
    supportsProviderSelection: false,
    homepage: 'https://cursor.sh',
  },
  {
    id: 'cline',
    name: 'Cline',
    description: 'Autonomous AI coding agent that operates in your terminal',
    icon: '\u{1F527}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.cline,
    detectionCommand: ['where', 'cline'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@cline/cline'],
    installUrl: 'https://github.com/cline/cline',
    launchCommand: ['cline'],
    supportsProviderSelection: true,
    configDocUrl: 'https://github.com/cline/cline#configuration',
    homepage: 'https://cline.ai',
  },
  {
    id: 'kilo-code',
    name: 'Kilo Code',
    description: 'Lightweight AI coding agent for quick code generation and editing',
    icon: '\u{26A1}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.kilo,
    detectionCommand: ['where', 'kilo'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', 'kilo-code'],
    launchCommand: ['kilo'],
    supportsProviderSelection: true,
    homepage: 'https://kilocode.ai',
  },
  {
    id: 'roo',
    name: 'Roo',
    description: 'AI coding assistant for terminal with multi-file editing capabilities',
    icon: '\u{1F98D}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.roo,
    detectionCommand: ['where', 'roo'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@roo/cli'],
    installUrl: 'https://github.com/roo-ai/roo',
    launchCommand: ['roo'],
    supportsProviderSelection: true,
    homepage: 'https://roo.ai',
  },
  {
    id: 'continue',
    name: 'Continue CLI',
    description: 'Open-source AI code assistant with configurable model backends',
    icon: '\u{1F504}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.continue,
    detectionCommand: ['where', 'continue'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@continuedev/continue'],
    installUrl: 'https://github.com/continuedev/continue',
    launchCommand: ['continue'],
    supportsProviderSelection: true,
    configFilePath: '~/.continue/config.json',
    configDocUrl: 'https://docs.continue.dev',
    homepage: 'https://continue.dev',
  },
  {
    id: 'amp-cli',
    name: 'Amp CLI',
    description: 'AI-powered terminal for command generation and automation',
    icon: '\u{1F3B5}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.amp,
    detectionCommand: ['where', 'amp'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@amp/cli'],
    launchCommand: ['amp'],
    supportsProviderSelection: true,
    homepage: 'https://amp.ai',
  },
  {
    id: 'qwen-code',
    name: 'Qwen Code',
    description: 'Alibaba\'s Qwen-based AI coding agent for terminal',
    icon: '\u{1F30D}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.qwen,
    detectionCommand: ['where', 'qwen'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', '@qwen/code'],
    installUrl: 'https://github.com/QwenLM/Qwen',
    launchCommand: ['qwen'],
    supportsProviderSelection: true,
    homepage: 'https://qwenlm.github.io',
  },
  {
    id: 'deepseek-tui',
    name: 'DeepSeek TUI',
    description: 'Terminal-based AI assistant powered by DeepSeek models',
    icon: '\u{1F50D}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.deepseek,
    detectionCommand: ['where', 'deepseek-tui'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', 'deepseek-tui'],
    installUrl: 'https://github.com/deepseek-ai/deepseek-tui',
    launchCommand: ['deepseek-tui'],
    supportsProviderSelection: true,
    homepage: 'https://deepseek.com',
  },
  {
    id: 'jcode',
    name: 'jcode',
    description: 'Lightweight terminal AI coding agent for rapid prototyping',
    icon: '\u{1F4DD}',
    category: 'coding',
    color: AGENT_PRESET_COLORS.jcode,
    detectionCommand: ['where', 'jcode'],
    installMethod: 'npm',
    installCommand: ['npm', 'install', '-g', 'jcode'],
    launchCommand: ['jcode'],
    supportsProviderSelection: true,
    homepage: 'https://github.com/jcode',
  },
];

export function getAllAgents(): AgentDefinition[] {
  return agentDefinitions;
}

export function getAgentById(id: string): AgentDefinition | undefined {
  return agentDefinitions.find(a => a.id === id);
}

export function getAgentsByCategory(category: string): AgentDefinition[] {
  return agentDefinitions.filter(a => a.category === category);
}

export const AGENT_CATEGORIES = [
  { id: 'coding', label: 'Coding Agents', icon: '\u{1F4BB}' },
];
