//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retrieval_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub session_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub updated_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub event_count: Option<i32>,
    pub file_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_vector: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub indexed_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::retrieval_chunks::Entity")]
    RetrievalChunks,
    #[sea_orm(has_many = "super::retrieval_events::Entity")]
    RetrievalEvents,
    #[sea_orm(has_many = "super::retrieval_files::Entity")]
    RetrievalFiles,
}

impl Related<super::retrieval_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrievalChunks.def()
    }
}

impl Related<super::retrieval_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrievalEvents.def()
    }
}

impl Related<super::retrieval_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrievalFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
