//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retrieval_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub event_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_vector: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::retrieval_chunks::Entity")]
    RetrievalChunks,
    #[sea_orm(
        belongs_to = "super::retrieval_sessions::Entity",
        from = "Column::SessionId",
        to = "super::retrieval_sessions::Column::SessionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RetrievalSessions,
}

impl Related<super::retrieval_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrievalChunks.def()
    }
}

impl Related<super::retrieval_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrievalSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
