//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub session_id: String,
    #[sea_orm(column_type = "Text")]
    pub display_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub event_count: Option<i32>,
    pub file_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub embedding_vector: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub indexed_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_heartbeat_at: Option<String>,
    pub heartbeat_timeout_seconds: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_metadata: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_state: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::checkpoints::Entity")]
    Checkpoints,
    #[sea_orm(has_many = "super::decisions::Entity")]
    Decisions,
    #[sea_orm(has_many = "super::events::Entity")]
    Events,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::insights::Entity")]
    Insights,
    #[sea_orm(has_many = "super::patterns::Entity")]
    Patterns,
    #[sea_orm(has_many = "super::session_status_history::Entity")]
    SessionStatusHistory,
}

impl Related<super::checkpoints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkpoints.def()
    }
}

impl Related<super::decisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Decisions.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::insights::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Insights.def()
    }
}

impl Related<super::patterns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patterns.def()
    }
}

impl Related<super::session_status_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionStatusHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
